### ISSUE TITLE
Unfinished paragraph in wiki

### ISSUE THREAD

**Issue by skade** [postmates/cernan#188]
There's an unfinished paragraph in the wiki: it abruptly ends mid-sentence.

https://github.com/postmates/cernan/wiki/Sinks#native

**Comment by blt** [comment]
Huh! I'll correct that. Thank you.

**Comment by blt** [comment]
Corrected. https://github.com/postmates/cernan/wiki/Sinks/_compare/eec43af88a3ea987441069fc4c43fa108770c2c4...30c8e8e144b8961cda71498a2e083206e885e687 Thanks again!
