### ISSUE TITLE
Flushes do not travel through filters

### ISSUE THREAD

**Issue by blt** [postmates/cernan#196]
Take a look at what modifies [`flush_sends`](https://github.com/postmates/cernan/blob/d748c9eb416892974eb77438ab826626a95f72f0/src/bin/cernan.rs#L76). Notice that only the sinks are being added to flush_sends and none of the filters. This means that the filters' `tick` will never be called, a violation of the programming model. 

I seem to recall that @tsantero and I punted on this problem. Consider the following case:

```
statsd -> a_filter
native -> b_filter
a_filter -> influxdb
b_filter -> influxdb
```

If we put flushes in at the level of `a_filter` and `b_filter` then influxdb will get two flushes. We ought to have flushes going through filters. 

While no solution occurred to us at the time -- @tsantero correct me if I'm wrong -- but it seems to me now that we might add an additional bit of data into the `metric::Event::TimerFlush`: an increasing counter. Sources can ignore a `TimerFlush` they've already seen. This implies one counter's worth of storage extra per sink. If we _also_ make the `FlushTimer` source emit one flush per second that'll free us up to do independent `flush_intervals` per source, as per #74. This does imply slightly higher load through hopper, but that's fine at one-per-second now that hopper does memory pass-through. Also! It simplifies the filters' `tick` as firing once-per-second.

**Comment by blt** [comment]
Related to #195.

**Comment by tsantero** [comment]
@blt this approach seems reasonable, with negligible overhead considering in exchange we'll gain a flush_interval per source

**Comment by blt** [comment]
@gliush how do you feel about resolving this bug with your active PR?
