### ISSUE TITLE
Implement a Kafka Sink

### ISSUE THREAD

**Issue by blt** [postmates/cernan#201]
We've got requests for cernan to report into [Apache Kafka](https://kafka.apache.org/). This should be a straightforward thing to achieve, based on the documentation [here](https://kafka.apache.org/protocol) full support is somewhat involved. I _believe_ integration with zookeeper is also required -- which is why we're 'hard' difficulty, rather than moderate -- but that's based only on a vague recollection.

**Comment by blakebarnett** [comment]
I'm pretty sure Kafka just uses ZK internally for leader election, etc.  But it would add it as a dependency, true.

**Comment by blt** [comment]
Done by @dparton
