### ISSUE TITLE
Implement an ElasticSearch Sink 

### ISSUE THREAD

**Issue by blt** [postmates/cernan#202]
We've had requests for cernan to report directly into [ElasticSearch](https://github.com/elastic/elasticsearch). Based on the information [here](https://www.elastic.co/guide/en/elasticsearch/guide/current/data-in-data-out.html) this should be a pretty direct bit of work.

**Comment by tfheen** [comment]
Maybe close this now that https://github.com/postmates/cernan/pull/268 is merged?

**Comment by blt** [comment]
Ah! Quite right. I forgot to tag this in the commit message. Thanks @tfheen!
