### ISSUE TITLE
Wavefront sink doesn't report zero counts, making accurate graphs difficult

### ISSUE THREAD

**Issue by bitglue** [postmates/cernan#247]
Wavefront doesn't interpret missing points as zeros: it interpolates the points. So when the points are something like `1, nil, nil, 1, nil, 1`, Wavefront will interpret that under some contexts as `1, 1, 1, 1, 1, 1` which of course is very wrong.

The `default()` function fixes this somewhat, but only at high zoom levels. `default` will only fill in a point if it's missing in a bucket, but after zooming out such that the Wavefront bin width is wider than the interval between the points, the results become inaccurate.

**Comment by blt** [comment]
I reached out to Wavefront to get their comments on sending zeros. Excerpts follow: 

> Yes having cernan send zeros is one option to help create a consistent graph. However this can be dangerous in times where the metric being reported is a counter and sending zero points will not be a true indication of the level of counting that is occurring.

With regard to cernan's [internal model](https://github.com/postmates/cernan/wiki/Data-Model#aggregation) for ephemeral SUM | SUMMARIZE this is fine. A SET probably ought to still kick a nil toward wavefront. This isn't an issue for persistent telemetry. The [Sources](https://github.com/postmates/cernan/wiki/Data-Model#aggregation) page discuss how different ingest protocols map to the internal model. 

> As for timeseries not being consistent across all zoom levels. The issue is with the bucketing of points. In the chart menu you can select what kind of aggregations are used in buckets. A bucket is basically the aggregation of several points into one point when for example the zoom level is very large (over a week) and the source is reporting every second. There is no way that you could see points representing 1-second on your computer monitor when there is 600k seconds in a week. So we bucket points depending on your computer resolution and browser window size to help display the data. I cannot make a general recommendation on how to have more consistent values across all zoom levels until I see an example.

> A general rule of thumb though is to change the aggregation under Chart > General > Summarize By setting to fit the kind of data you want to see at all levels of zoom. Max and Min are quite consistent across time windows for time series with large spontaneous spikes or deep troughs as well as counters. Average can be quite consistent for timeseries that oscillate around a specific value.

These comments make me wonder how effective filling in the blanks will be. Easy enough to make enabling zeros a configurable thing.

**Comment by bitglue** [comment]
That doesn't make any sense. Maybe they thought "counter" means the sort that is increasing, where `rate()` would be appropriate?

**Comment by blt** [comment]
I'm honestly not sure. I'll see about getting that clarified.

**Comment by blt** [comment]
Okay! This issue is now getting worked. Here's the deal, we want to:

1. avoid shipping multiple runs of zeros
2. pad long null runs with zeros on either side

Example of the first:

`[1,1,0,0,0,0,0,0,0,1]` -> `[1,1,0,nul,0,1]`

Example of the second:

`[1,1,nul,1]` -> `[1,1,0,nul,0,1]`

**Comment by blt** [comment]
Closed by #293, #286, #288, #289
