### ISSUE TITLE
Internal source has a potentially unbounded buffer

### ISSUE THREAD

**Issue by blt** [postmates/cernan#260]
The internal source, if not given any forwards, will store its members indefinitely. We need to make it so that in the event of there being no forwards for this source it simply drops elements, instead of keeping them in the `VecDeque`.

**Comment by blt** [comment]
In particular, what needs to be done here is that in `src/sources/internal.rs` we need to create a toggle inside `Internal` that will dump or store `metric::Telemetry` which comes through. This toggle will be set when we construct `InternalConfig` in `src/config.rs`.

**Comment by imjacobclark** [comment]
Would be interested in working on this, could you provide mentorship? What's the best way to get in touch?

**Comment by blt** [comment]
@imjacobclark great! We can talk here or feel free to email me at the address listed in my bio.
