### ISSUE TITLE
Make default tags a thing

### ISSUE THREAD

**Issue by blt** [postmates/cernan#279]
It would be convenient for some users if cernan had a default set of tags. @blakebarnett is the primary contact for this feature. For users that do not use tags we'd want to add a `default-tags: Bool` option to cernan to avoid tags, false by default. 

Default tags we have so far:

* hostname 

Open to suggestions. 

- - - 

After further discussion, we now want default-tags to be a list, not a boolean. See https://github.com/postmates/cernan/issues/279#issuecomment-312074665 for more details.

**Comment by blakebarnett** [comment]
For consistency could we have it be `source = $HOSTNAME`?

**Comment by tfheen** [comment]
At the risk of bikeshedding, how about having `default-tags = [hostname, foo, bar]` (or maybe a map with keys and values), rather than a bool to turn them on and off? `default-tags = []` would make it be "no tags".

**Comment by blt** [comment]
@blakebarnett works for me. 

@tfheen Hmm, interesting idea. In the list form we'd just define in documentation what `foo` maps to? @blakebarnett would this form work for you?

**Comment by blakebarnett** [comment]
Yeah I like it

**Comment by tfheen** [comment]
Yeah, a default in docs, but it could also be amended by extra plugins, maybe? Not sure how complicated it needs to be, but a list feels a lot more flexible than just a bool with no real downsides.

**Comment by blt** [comment]
I'm for the list variant.

**Comment by blt** [comment]
@blakebarnett thinking on this some more to grab hostname I can run `hostname` on unix-like systems. Instead of that, how would it be if I allowed you to set tags by explicitly referencing environment variables? The current tag config looks like so:

```yaml
[tags]
source = "cernan"
```

It could be extended to something like:

```yaml
[tags]
source = "cernan"
hostname = { environment: true, value: "HOSTNAME" }
```

At start up cernan would read `HOSTNAME` from the environment and store that as the default-tag `hostname`. Would this work? 

I like that this approach does not require anything to be hard-coded.

**Comment by blakebarnett** [comment]
Agreed, sounds good.
