### ISSUE TITLE
Cernan needs a proper binning histogram

### ISSUE THREAD

**Issue by blt** [postmates/cernan#290]
As of 2f08dbc0c11f0089e6e798241045a76730c3559a the only summarization type that cernan supports is the [CKMS](https://github.com/postmates/quantiles#ckms---effective-computation-of-biased-quantiles-over-data-streams) from our quantiles. Quantile structures are great but suffer from the need to aggregate the structures before their data makes sense, as in Wavefront or Prometheus. This is _not_ a problem for binning histograms, that is histograms computed by using a client-supplied min/max range plus number of bins. Individual cernan instances are able to choose the same aggregating behaviour without coordination. 

We should extend the native protocol to include a HISTOGRAM summary type. I believe we will need: 

* a global configuration for default min/max
* a global configuration for default number of bins
* extension to the native protocol to include stream-specific min/max, bins

We may also choose to retarget statsd histogram/timers to this type. I'm unsure about this.

This is related to #66. 

@lynchc @bitglue relevant to your interests

**Comment by bitglue** [comment]
If we're re-targeting statsd, I'd be more inclined to do that at the client level to have the existing application code send histograms for the `.timer()` function, than change the statsd protocol semantics.

**Comment by blt** [comment]
@pulltab ^^

**Comment by blt** [comment]
@bitglue one thing I'm not clear about, if we have application code send histograms (as multiple counters?) is how we then interact with prometheus, since it does have a native histogram type. I guess we can send Prometheus multiple counters too but if we can get clients to send us that extra info I don't see where we come out behind.

**Comment by tfheen** [comment]
The individual bin width should be configurable. It's interesting to see if something takes 5 or 10ms, but probably not that interesting to know if it takes 1005 or 1010 ms.

**Comment by blt** [comment]
@tfheen looking at just the native protocol, my expectation is that the user will send the binning information along with each payload. Under discussion now is whether we extend that same behaviour into the statsd source by accepting a broader form of statsd payloads.

**Comment by bitglue** [comment]
The Prometheus data model for histograms is also multiple counters. There's just a bit of metadata that specifies the bin boundary. Prometheus uses the metadata for a function which estimates quanties based on the histogram. Prometheus clients calculate the binning and expose multiple counters with metadata.

Example: https://github.com/prometheus/client_python/blob/master/prometheus_client/core.py#L862-L868

**Comment by blt** [comment]
This is now complete and is documented.
