### ISSUE TITLE
Support HISTOGRAM in wavefront sink 

### ISSUE THREAD

**Issue by blt** [postmates/cernan#308]
As of this writing the wavefront sink cannot properly ship histograms, in fact they are ignored. If 
 #307 is to land we're going to need to correct that. We can either:

  * ship the bins + count information or 
  * estimate quantiles from histogram, ship estimate 

I'm not so sure of the wavefront query language, if users would be able to construct a quantile estimate from shipped bins + count. Open to suggestions. 

@bitglue @pulltab

**Comment by blt** [comment]
Related to #290

**Comment by bitglue** [comment]
I vote just ship the bins. Doing quantile estimation in Cernan means trying to guess about what population should be estimated. I don't believe there's any way to do quantile estimation in the Wavefront query language.

With the count information it's still possible with a little tedium to construct queries, such as "what percentage of requests were over 150ms?" which addresses the use case of measuring compliance with an SLA. i.e, we couldn't query "what's the nth percentile?" but we could query "what percentile is x?"

One could also query all the bins and make a stacked area chart. Wavefront will stack them in an arbitrary order which isn't ideal, but with a little squinting it still provides useful information.
