### ISSUE TITLE
Implement Sink for Google PubSub

### ISSUE THREAD

**Issue by jenglund** [postmates/cernan#331]
One option used for (near) real-time event processing is Apache Beam, which can be run in the cloud via Google Dataflow. Beam supports both batch/bounded pipelines and streaming/unbounded pipelines. 

The only streaming source (presently) available in the Python SDK is Google PubSub. So, anyone who would like to use Dataflow for data analysis needs that data to be published to one or more Google PubSub topics. Thus, it would make sense for Cernan to support this as an option.

Individual Publishes are capped at about 10MB, and the default quota is 100MB/sec but can be expanded indefinitely.

Messages may have up to 100 attributes attached (each with a 256 byte key and 1024 byte value limit), but note that attributes are discarded in Dataflow's PubSub source (at least for now). They're still useful to set in most any other application, it's just worthwhile to note that this discrepancy exists.

**Comment by blt** [comment]
@jenglund I added some labels to this. Really looking forward to this landing.
