### ISSUE TITLE
Handle Signals 

### ISSUE THREAD

**Issue by blt** [postmates/cernan#34]
It would be very useful for integration testing if SIGINT were to cause backends to flush and then result in program exit.

**Comment by pulltab** [comment]
Another use case for signal handling: being able to promise at least once delivery on certain sinks.  

For example, consider a scenario where we want to ensure a sink delivers log messages at least once.  As an administrator, I can ensure tooling exists to bring down the system gracefully, however,  said tooling needs to inform Cernan to both shut down source ingestion and synchronously flush the configured sinks.  Making use of signals to accomplish this represents the path of least-astonishment.

**Comment by pulltab** [comment]
First step - #333

**Comment by blt** [comment]
I'd say #339 fit the bill!
