### ISSUE TITLE
async story

### ISSUE THREAD

**Issue by ibotty** [postmates/cernan#350]
Does it make sense to convert cernan to use tokio? I'd like to get my hands dirty converting non-toy-examples so if there is interest, I might contribute some time.

**Comment by blt** [comment]
It absolutely does! @pulltab is working on that very thing in https://github.com/postmates/cernan/tree/ipc-shutdown. He's focusing on using mio rather than tokio but it's well worth talking to him and getting a sense of where you can lend a hand.
