### ISSUE TITLE
Delay filters tolerance

### ISSUE THREAD

**Issue by doubleyou** [postmates/cernan#364]
I'm looking at https://github.com/postmates/cernan/wiki/FiltersDelay, and the description of the `tolerance` parameter says "the maximum number of seconds a point may be to pass this filter". This sounds ambiguous, at first I thought it was something akin to Riemann, where every "point" actually lasts a period of time. But, according to the description above, it seems like this is the maximum point's age in seconds to pass the filter.

**Comment by blt** [comment]
Ah yeah, you know, you're right. That is strangely worded. How about:

> the maximum difference (in seconds) between the current time and a point's such that the point is allowed to pass this filter

?

**Comment by doubleyou** [comment]
👍

**Comment by blt** [comment]
Cool. Updated.
