### ISSUE TITLE
Summaries in the prometheus sink exhibit incorrect behavior once points stop being sent

### ISSUE THREAD

**Issue by dparton** [postmates/cernan#366]
Currently the quantiles reported to prometheus continue at the same value when points stop being received. Ideally, the summarization window should "continue forward," treating no new points as null. This is probably best explained with an example:

Suppose you have some event named "foo_latency" (and with it, foo_latency_count, foo_latency_sum). Suppose also that the summarization window is 30 seconds. Then, 30 seconds after the last point for foo_latency has been received, the metrics associated with it should no longer report to the scraper. Alternatively, I would consider reporting zero as an acceptable approach as well.

Image:
<img width="1424" alt="screen shot 2017-12-12 at 11 11 46 am" src="https://user-images.githubusercontent.com/12650318/33903156-6727cd36-df45-11e7-8501-4336512bfe66.png">

The above image is a graph of random summary data being reported. First the values were always between 1 and 10, and later they were between 1 and 100.  The left axis represents the number of samples coming in over the previous 30 seconds, and the right axis lists each of the quantiles. It is readily apparent that the quantiles remain constant (flatline) once points stop coming in, indicated by the yellowish-orange "samples" lines drops to zero.

**Comment by blt** [comment]
@dparton is this something you're interested in working? If not, I'll bump it back to 1.0.
