### ISSUE TITLE
Issues with the native source

### ISSUE THREAD

**Issue by doubleyou** [postmates/cernan#368]
I tried to make a script that would allow reporting arbitrary metrics using a native source: https://gist.github.com/doubleyou/1e75fff02ff26b9a9f2fd5ca6c6d3417

It's a combination of the compiled `.proto` file and an actual script that implements CLI and network.

Payload length is calculated in accordance with https://docs.python.org/2/library/struct.html and https://github.com/postmates/cernan/blob/master/resources/protobufs/native.proto. The rest is pretty much packing a bunch of values into a protobuf packet.

Two issues arise when I try to test it:

1. Upon start, cernan reports the following in the logs:
```
cernan_1             | thread '<unnamed>' panicked at 'Unable to bind to TCP socket: Error { repr: Os { code: 98, message: "Address already in use" } }', /checkout/src/libcore/result.rs:906:4
cernan_1             | note: Run with `RUST_BACKTRACE=1` for a backtrace.
cernan_1             | thread '<unnamed>' panicked at 'Unable to bind to TCP socket: Error { repr: Os { code: 98, message: "Address already in use" } }', /checkout/src/libcore/result.rs:906:4
```

It's worth noting that changing the port doesn't affect that. Seems to be a race condition or something?

2. However, seems like later on cernan actually starts listening on the port, because when I run the script (my specific example: `./houston.py service.restarts 1.0 1 service=test 1.0`), I see the following error in the logs:
```
cernan_1             | thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /checkout/src/liballoc/vec.rs:1561:14
```

Adding `RUST_BACKTRACE=full` didn't really help, I'll probably try to rebuild cernan with debug info, at least to see where the actual calls are happening.

**Comment by blt** [comment]
@doubleyou just to confirm, are you working off 6313149c5022164c722b3e9fe4a282d58a367865? We recently landed mio handling to cernan and something goofy may be up.

**Comment by doubleyou** [comment]
Good question, it was actually an arbitrary master build from a few days ago. Should I try the last release?

**Comment by doubleyou** [comment]
Hmm, but then, I guess, I'll have trouble with our InfluxDB integration :)

**Comment by doubleyou** [comment]
And, obviously, we should actually start using a specific git ref from now on :)

**Comment by doubleyou** [comment]
I'm positive we are using an older version than the commit you posted, Brian. Our build of cernan is about a week old, while that commit is from 2 days ago.

**Comment by blt** [comment]
@doubleyou got it. Hmm, well, would it be much trouble to update to the latest master? Your InfluxDB fix is in. 

We can meet you where you are, of course, if you can't.

**Comment by doubleyou** [comment]
Tried on the latest master, with `debug = true` in `Cargo.toml`. Same results. Here's the full backtrace for requests failing:
```
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /checkout/src/liballoc/vec.rs:1561:14
stack backtrace:
   0:     0x557a025f2063 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h8ed7485deb8ab958
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x557a025efd48 - std::panicking::default_hook::{{closure}}::h0088fe51b67c687c
                               at /checkout/src/libstd/sys_common/backtrace.rs:69
                               at /checkout/src/libstd/sys_common/backtrace.rs:58
                               at /checkout/src/libstd/panicking.rs:381
   2:     0x557a025ef1a5 - std::panicking::rust_panic_with_hook::h25b934bb4484e9e0
                               at /checkout/src/libstd/panicking.rs:397
                               at /checkout/src/libstd/panicking.rs:577
   3:     0x557a025eec28 - std::panicking::begin_panic::h59483e27e93d7bc6
                               at /checkout/src/libstd/panicking.rs:538
   4:     0x557a025eeba9 - std::panicking::begin_panic_fmt::h5f221297e8a3dbdb
                               at /checkout/src/libstd/panicking.rs:522
   5:     0x557a0260689a - core::panicking::panic_fmt::h4d1ab9bae1f32475
                               at /checkout/src/libstd/panicking.rs:498
   6:     0x557a02606418 - core::panicking::panic_bounds_check::h00738207f5476c9a
                               at /checkout/src/libcore/panicking.rs:58
   7:     0x557a0233a005 - cernan::util::send::h43223daaf103057d
   8:     0x557a02359908 - std::sys_common::backtrace::__rust_begin_short_backtrace::h63e6a1f167c77cc2
   9:     0x557a02356949 - <F as alloc::boxed::FnBox<A>>::call_box::hc49f35ebf3e6ff39
  10:     0x557a02602d07 - std::sys::imp::thread::Thread::new::thread_start::hbaf1b5aa1ca8e3ea
                               at /checkout/src/liballoc/boxed.rs:736
                               at /checkout/src/libstd/sys_common/thread.rs:24
                               at /checkout/src/libstd/sys/unix/thread.rs:90
  11:     0x7fb7fa1966b9 - start_thread
  12:     0x7fb7f9cb63dc - clone
  13:                0x0 - <unknown>
```

Interestingly, it looks identical to the errors with port openings (first issue from my original report).

**Comment by blt** [comment]
Cool. Can I get a copy of the cernan config you're using?

**Comment by doubleyou** [comment]
```
data-directory = "/tmp/cernan"
scripts-directory = "/opt/cernan/etc/scripts/"

flush-interval = 10

[sources]
  [sources.native]
  ip = "127.0.0.1"
  port = 1972
  forwards = ["sinks.console"]

  [sources.statsd.primary]
  enabled = true
  port = 8125
  forwards = ["sinks.influxdb"]

    [sources.statsd.primary.mapping.default]
    mask = ".*"
    bounds = [0.0, 0.1, 10.0, 100.0]

  [sources.graphite.primary]
  enabled = true
  port = 2004
  forwards = ["filters.programmable.collectd_scrub"]

[filters]

  # Read and parse collectd's input.
  [filters.programmable.collectd_scrub]
  script = "collectd_scrub.lua"
  forwards = ["filters.delay.telemetry"]

  # Filter out metrics that are more than 10 seconds old. See
  # https://github.com/postmates/cernan/wiki/FiltersDelay
  [filters.delay.telemetry]
  tolerance = 10
  forwards = ["filters.flush_boundary.telemetry"]

  # Wait for 2 seconds before sending the metrics to InfluxDB. See
  # https://github.com/postmates/cernan/wiki/FiltersFlushBoundary
  [filters.flush_boundary.telemetry]
  tolerance = 2
  forwards = ["sinks.influxdb"]

[sinks]
  [sinks.influxdb]
  secure = false
  bin_width = 1
  host = "<censored>"
  port = 8086
  db = "mydb"

  [sinks.console]
  bin_width = 1
  flush_interval = 5

[tags]
source = "cernan"
hostname = { environment = true, value = "HOSTNAME" }
```

In the meantime, I'm considering to make a minimal config and see if that affects anything.

**Comment by doubleyou** [comment]
Confirmed, same issues with this minimal config:

```
data-directory = "/tmp/cernan"

flush-interval = 10

[sources]
  [sources.native]
  ip = "127.0.0.1"
  port = 1972
  forwards = ["sinks.console"]

[sinks]

  [sinks.console]
  bin_width = 1
  flush_interval = 5

[tags]
source = "cernan"
```

**Comment by blt** [comment]
Heard, thank you. I'll see what I can turn up.

**Comment by blt** [comment]
@doubleyou okay! We've identified the problem and will have a patch ready for your inspection directly.

**Comment by doubleyou** [comment]
@blt: Cool, thanks for the help!

**Comment by blt** [comment]
@doubleyou oh crap, so, one part of the problem here – maybe the whole thing! – is a configuration issue. Which, implies a documentation issue on our part. 

There can be multiple native sources and you have to distinguish them by name. So instead of:

```
[sources]
  [sources.native]
  ip = "127.0.0.1"
  port = 1972
  forwards = ["sinks.console"]
```

you want

```
[sources]
  [sources.native.primary]
  ip = "127.0.0.1"
  port = 1972
  forwards = ["sinks.console"]
```

**Comment by blt** [comment]
@doubleyou I don't have python installed on my personal machine. Does `houston` – nice name, by the way – run correctly with the configuration change?

**Comment by blt** [comment]
https://github.com/postmates/cernan/wiki/SourcesNative is now corrected.

**Comment by doubleyou** [comment]
Wow. That does seem to have solved everything. I can see now metrics showing up in the console sink.

**Comment by blt** [comment]
https://github.com/postmates/cernan/wiki/Configuration is now corrected.

**Comment by doubleyou** [comment]
Awesome, thanks again for the help! I ran the full integration, metrics show up correctly now.

**Comment by gliush** [comment]
@blt: What do you think, is it possible to implement a config checker that might find and warn about all possible issues in the config? E.g. this one and some known others?
I don't like an idea when bad user config causes run-time panics, we should try to avoid it.

**Comment by blt** [comment]
@gliush I agree whole heartedly. I'm sure it is possible but I haven't looked into it with any depth. The library that we use right now is just plain [toml](https://crates.io/crates/toml), pretty silent with regard to config schema checking. 

Open to ideas here.

**Comment by gliush** [comment]
@blt:
I believe there should be two separate pieces:
- List of properties of the system (like, if we have A + B in config, then we should always have C)
- Some checker that will check the properties.

List of properties depends on code. I'm not sure that it's worth having it separately, because it will be outdated quite soon. It should be something like "@spec + Dializer" in Erlang world. 
The only idea that came to my mind is:
- for each functionality that requires config semantic check - prepare a function that will be run before the main functionality (or with special command).
- run all such functions before the main functionality and give some diagnostics in case of an error.

What do you think?

**Comment by blt** [comment]
@gliush that sounds like a plan to me. Very happy to accept patches toward that end.

**Comment by gliush** [comment]
Let me create an issue about it, let's continue discussing the idea there...
