### ISSUE TITLE
Statsd timings seem to break cernan

### ISSUE THREAD

**Issue by doubleyou** [postmates/cernan#371]
## Steps to reproduce:

1. Build cernan (https://github.com/postmates/cernan/commit/a4da52dc93eef606a3667dc6ad664e5d7248937f would work, but I have reproduced this on older versions too).

2. Start it with the following config:
```
data-directory = "/tmp/cernan"

flush-interval = 2

[sources]

  [sources.statsd.primary]
  enabled = true
  port = 8125
  forwards = ["sinks.console"]

    [sources.statsd.primary.mapping.default]
    mask = ".*"
    bounds = [0.0, 0.1, 10.0, 100.0]

[sinks]
  [sinks.console]
  bin_width = 1
```

3. `pip install git+https://github.com/postmates/pystatsd` (virtualenv recommended).

4. In Python repl, run the following:
```
import pystatsd
pystatsd.timing('test.timing', 50)
```

## What happens

Output with `RUST_STACKTRACE=full`:
```
cernan_1             | thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: CannotSetError', /checkout/src/libcore/result.rs:906:4
cernan_1             | stack backtrace:
cernan_1             |    0:     0x563ec43a0063 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h8ed7485deb8ab958
cernan_1             |                                at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
cernan_1             |    1:     0x563ec439dd48 - std::panicking::default_hook::{{closure}}::h0088fe51b67c687c
cernan_1             |                                at /checkout/src/libstd/sys_common/backtrace.rs:69
cernan_1             |                                at /checkout/src/libstd/sys_common/backtrace.rs:58
cernan_1             |                                at /checkout/src/libstd/panicking.rs:381
cernan_1             |    2:     0x563ec439d1a5 - std::panicking::rust_panic_with_hook::h25b934bb4484e9e0
cernan_1             |                                at /checkout/src/libstd/panicking.rs:397
cernan_1             |                                at /checkout/src/libstd/panicking.rs:577
cernan_1             |    3:     0x563ec439cc28 - std::panicking::begin_panic::h59483e27e93d7bc6
cernan_1             |                                at /checkout/src/libstd/panicking.rs:538
cernan_1             |    4:     0x563ec439cba9 - std::panicking::begin_panic_fmt::h5f221297e8a3dbdb
cernan_1             |                                at /checkout/src/libstd/panicking.rs:522
cernan_1             |    5:     0x563ec43b489a - core::panicking::panic_fmt::h4d1ab9bae1f32475
cernan_1             |                                at /checkout/src/libstd/panicking.rs:498
cernan_1             |    6:     0x563ec4026b1b - core::result::unwrap_failed::h8824197d9878f263
cernan_1             |    7:     0x563ec410d124 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb9f913159e607447
cernan_1             |    8:     0x563ec410a986 - <F as alloc::boxed::FnBox<A>>::call_box::hac99f2e9ac949407
cernan_1             |    9:     0x563ec43b0d07 - std::sys::imp::thread::Thread::new::thread_start::hbaf1b5aa1ca8e3ea
cernan_1             |                                at /checkout/src/liballoc/boxed.rs:736
cernan_1             |                                at /checkout/src/libstd/sys_common/thread.rs:24
cernan_1             |                                at /checkout/src/libstd/sys/unix/thread.rs:90
cernan_1             |   10:     0x7f5d9e3ab6b9 - start_thread
cernan_1             |   11:     0x7f5d9decb3dc - clone
cernan_1             |   12:                0x0 - <unknown>
```

Interestingly, when I use an InfluxDB sink, cernan stops reporting data there at all, once this error occurs. It keeps printing things out to the console though.

Also, interestingly, I tried to reproduce this on postal-console-stage and things didn't break there. Hard to tell how much the versions of pystatsd and cernan differ there. If anything, pystatsd way of serializing timings seems legit: https://github.com/postmates/pystatsd/blob/master/pystatsd/pystatsd.py#L179.

**Comment by blt** [comment]
Huh. Let me see if I can reproduce.

**Comment by doubleyou** [comment]
Confirmed on the lower level, just sending a UDP packet looking like `test:123|ms` breaks it for me.

**Comment by blt** [comment]
I just confirmed the same way on latest master. I'm now going to re-run on the last tagged release.

**Comment by blt** [comment]
That's... astonishing. Same thing on 0.8.6. I'm building on nightly and will now switch to stable. Good god.

**Comment by pulltab** [comment]
@doubleyou @blt The issue presents itself when mappings are used.  If you remove that section from the config, then timings work as expected.

**Comment by blt** [comment]
Okay, whew, well it's still a bad break but less worrisome than others. Will work and let you know when I have a fix for inspection.

**Comment by doubleyou** [comment]
Wait, I could just not use mappings at all?

I love you, John.

**Comment by doubleyou** [comment]
Confirmed, works for me without mappings.

**Comment by blt** [comment]
@doubleyou oh yeah, the mappings are optional. https://github.com/postmates/cernan/wiki/SourcesStatsd#mapping allows you to switch between a summary representation of timers (default) and a histogram representation. 

Did the documentation read like mappings were mandatory?

**Comment by doubleyou** [comment]
@blt: good question; I attribute that mostly to my lack of attention, since I was basically copy-pasting the existing examples and trying to minimize them :)

Reading the mappings paragraph does deliver the idea that they are optional, but maybe having a minimal configuration example as a separate thing would have been more declarative.

**Comment by blt** [comment]
@doubleyou that's a good suggestion. I'll make that happen.
