### ISSUE TITLE
Consider setting `panic=abort` for release builds

### ISSUE THREAD

**Issue by blt** [postmates/cernan#406]
We've had repeat reports that errors in one part of cernan will leave it partially available: a thread'll abort but the upstream nodes will keep pushing into queues etc etc. 

If we set `panic=abort` then all of cernan will go offline but the startup harness will be able to choose to restart it.

**Comment by blt** [comment]
@blakebarnett @pulltab @dparton thoughts?

**Comment by tfheen** [comment]
I think just exiting so the init system can restart it makes a lot of sense, having it half-live has very limited value.

**Comment by pulltab** [comment]
I believe this is an easy fix which will solve one class of failures.  The more complete solution is to be able to detect all situations where a worker thread is failing to make forward progress.  This will require application layer heartbeats and supervision of subordinate threads.
