### ISSUE TITLE
Deprecate & Remove Rusoto Backed Sinks

### ISSUE THREAD

**Issue by pulltab** [postmates/cernan#426]
This would include the following sinks: 

* Kinesis
* Firehose

My reasoning:

* Rusoto is a very large project (wrt dependencies).

* Current releases of rustoto are failing within the context of pulling credentials from IAM.  This renders both of the afore mentioned sinks useless within our own infrastructure.   I am not comfortable supporting modules which are not, nor have not, been actively used in a production capacity.

Does anyone have vested interest in keeping either of these sinks around?

**Comment by pulltab** [comment]
@blt @dvdklnr ^^

**Comment by blt** [comment]
@pulltab Absent someone willing to champion these sinks I have no interest in keeping them around. The maintenance cycle around them has been tough while rusoto stabilizes. 

This'd also pull firehose, no?

**Comment by pulltab** [comment]
Doh, I meant firehose.  Not elasticsearch.  Will update my original post.

**Comment by matthewkmayer** [comment]
The async release of Rusoto fixes the occasional issues with sourcing credentials from instance profiles. 😄 

If deprecating use of Rusoto in `cernan` is the path taken, no worries. I understand how difficult it is to work with packages under heavy development.

**Comment by blt** [comment]
@matthewkmayer we're kind of in a sticky spot. I have gotten feedback that cernan integrating with AWS is useful but our primary use-case is shifting away from AWS stuff. Which, absent some kind soul donating work, means that rusoto's going to get more and more out of data as time goes on. :/

**Comment by blt** [comment]
Resolved.
