### ISSUE TITLE
Q3 2018 Planning

### ISSUE THREAD

**Issue by pulltab** [postmates/cernan#447]
Hello, folks.

I am opening this thread so that we can establish and discuss development priorities for Q3 2018.  

For my part, I have jotted down the following Q3 objectives:

* Enable true synchronous publication for the Avro source.  This will involve some notion of shard state between source, sink, and maybe filter threads which I plan on discussing in another issue (will link here when it is started).

* Integrate ThreadPool into bin/cernan.rs so that it can respond to panics in subordinate threads.  To date, we have had to be real careful about when a subordinate thread can panic.  This will open the door for thread supervision, giving us options wrt restart strategies.

* (Stretch Goal) Optimize file source for CPU and memory usage when frequent truncation is present.
 
cc @blt @blakebarnett

**Comment by blt** [comment]
I am pro all these things. WRT to the stretch goal, do we have numbers on the issue or a way to reproduce? 

For me, I'd like to see more housekeeping stuff in place. 

  * Improve the state of clippy lints against cernan, make the stable ones mandatory.
  * Expand the fuzzing of cernan. Right now this is ad hoc.
  * Expand the benchmarking of cernan. Also ad hoc.

**Comment by blt** [comment]
@pulltab objections to closing this?

**Comment by pulltab** [comment]
Nope!  Good bye, Q3.
