### ISSUE TITLE
Run rustfmt in Travis

### ISSUE THREAD

**Issue by josephglanville** [postmates/cernan#453]
Requires fixing `.rustfmt.toml` to be compatible with current `rustfmt`, formatting all the code and adding install of `rustfmt` via `rustup` to `.travis.yml` and calling `cargo fmt --check`.

**Comment by blt** [comment]
We had this going back before rustfmt was 1.0. IIRC @pulltab found it really annoying because of slight differences in the rustfmt versions we'd end up having. 

I'm for having rustfmt run in Travis, so long as it doesn't annoy John.

**Comment by josephglanville** [comment]
Yeah it seems to have experienced.. turbulent changes in the past. Hopefully post 1.0 this is less of an issue as life is too short to wonder how code should be formatted, I would much prefer the computer decided it for me. :)

**Comment by blt** [comment]
Oh yeah, absolutely.
