### ISSUE TITLE
Prometheus Sink - Make gzip Compression Optional

### ISSUE THREAD

**Issue by pulltab** [postmates/cernan#456]
On a system which is cpu bound and exposes a large number of metrics, the usage of gzip in the prometheus sink results in undesired CPU spikes.

We should make gzip encoding a config option.  This will save the cpu overhead, making the prometheus sync more IO bound.

**Comment by lynchc** [comment]
More important than the cpu spikes is that often the cernan process will fail to complete the metrics response in less than 10 seconds resulting in a failed scrape
