### ISSUE TITLE
Histograms and Configurable Bins

### ISSUE THREAD

**Issue by bitglue** [postmates/cernan#66]
In order to preserve information about the distribution of request times or similar data, we can't rely on percentiles: there's no correct way to later aggregate two percentiles to get another percentile. A mean of a percentiles isn't usually what you want.

What we _can_ do is calculate histograms for each reporting period, then report each bin of that histogram, for each flush interval, to Wavefront. From Wavefront's perspective it's just a bunch of separate metrics, but we can reassemble them and calculate a histogram for the distribution of some values for arbitrary intervals without loss of information.

The tricky part here is communicating from the application to Cernan what the bins should be. Statsd can be [configured to calculate histograms](https://github.com/etsy/statsd/blob/master/docs/metric_types.md) in this way, but it involves defining the bins in statsd's config file which is awkward to realize.

So I propose an extension to the statsd protocol so applications can communicate to cernan at application start the desired histogram bins. Proposed format:

`metric.name:-inf,1,10,100,inf|h`

This configures four bins for the metric `metric.name`:
- less than 1
- [1, 10)
- [10, 100)
- greater than or equal to 100

Applications can send these each time they start, and Cernan will write them to the filesystem so they don't need to be sent again if Cernan restarts.

**Comment by pulltab** [comment]
Some points from offline discussion:

1.  The sort of one-time configuration suggested would best be served as an RPC like mechanism (or at least a mechanism with some form of acknowledgment) instead of piggy-backed onto the statsd UDP protocol.  Some reasoning:
    * Even in our own infra, many services startup in a race condition with Cernan.  If these datagrams were emitted once and missed then confusion would be incurred.

    * More unrealistic, but nothing is stopping these local datagrams from being dropped in other circumstances.

    Instead, I would vote that we send such binning information along with the payload of a timing value.   This helps us deal with datagram loss in an honest way.  The downside here will be extra complexity cernan-side as it will have to deal with odd scenarios where users change an already established binning configuration.

2.  Use of the advanced feature should stay optional from the client perspective.  As such, cernan should have a configurable, default binning configuration.   When not specified, timer emissions can remain statsd compliant.   When specified, an extended datagram will be sent.

**Comment by blt** [comment]
This is completed and documented in [SourcesStatsd](https://github.com/postmates/cernan/wiki/SourcesStatsd#mapping).
